name: Run the qodo-cover-pr action (Python)

on:
  pull_request:
    branches:
      - main
    types:
      - labeled
      - opened
      - synchronize

permissions:
  pull-requests: write
  contents: write

jobs:
  run-qodo-cover-pr-python:
    if: |
      github.event.action == 'labeled' && github.event.label.name == 'qodo-cover' ||
      github.event.action == 'opened' || github.event.action == 'synchronize'
    runs-on: ubuntu-22.04

    steps:
      - name: Debug GitHub Event
        run: echo '${{ toJson(github.event) }}'

      - name: Checkout PR branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-dev python3-pip
          python3 --version

      - name: Install app dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r fastapi/requirements.txt

      - name: Qodo Cover
        uses: qodo-ai/qodo-ci/.github/actions/qodo-cover-pr@v0.1.12
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          project_language: python
          project_root: fastapi
          code_coverage_report_path: fastapi/coverage.xml
          test_command: "pytest --cov=. --cov-report=xml --cov-report=term"
          model: gpt-4o-2024-11-20
          desired_coverage: 70
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
